server:
  servlet:
    context-path: /
  connection-timeout: 6000000
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost/customerdb
    username: root
    password: root
    initialization-mode: always
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:/sql
    schemas: customerdb
    baseline-on-migrate: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: testemailuser8@gmail.com
    password: Test@123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  thymeleaf:
    prefix: classpath:/templates/email/
    suffix: .html
      
logging:
  level:
    org:
      hibernate:
        type: trace
        
haud:
  csv: /home/rosh/NeoSoft
  companyemail: roshtr321@gmail.com
  email:
    from: testemailuser8@gmail.com
    template:
      bday: bday
      
      
      
      
      